// GENERATED by `make gen` from the meshtastic-protobufs submodule. DO NOT EDIT.
#pragma once

#include <cstdint>

namespace esphome {
namespace meshtastic {

const char *role_name(uint32_t value);
bool role_is_deprecated(uint32_t value);
const char *hardware_model_name(uint32_t value);
bool hardware_model_is_deprecated(uint32_t value);

}  // namespace meshtastic
}  // namespace esphome
