// GENERATED by `make gen` from the meshtastic-protobufs submodule. DO NOT EDIT.
#include "enum_names.h"

namespace esphome {
namespace meshtastic {

const char *role_name(uint32_t value) {
  switch (value) {
    case 0: return "CLIENT";
    case 1: return "CLIENT_MUTE";
    case 2: return "ROUTER";
    case 3: return "ROUTER_CLIENT";
    case 4: return "REPEATER";
    case 5: return "TRACKER";
    case 6: return "SENSOR";
    case 7: return "TAK";
    case 8: return "CLIENT_HIDDEN";
    case 9: return "LOST_AND_FOUND";
    case 10: return "TAK_TRACKER";
    case 11: return "ROUTER_LATE";
    case 12: return "CLIENT_BASE";
    default: return "UNKNOWN";
  }
}

bool role_is_deprecated(uint32_t value) {
  switch (value) {
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const char *hardware_model_name(uint32_t value) {
  switch (value) {
    case 0: return "UNSET";
    case 1: return "TLORA_V2";
    case 2: return "TLORA_V1";
    case 3: return "TLORA_V2_1_1P6";
    case 4: return "TBEAM";
    case 5: return "HELTEC_V2_0";
    case 6: return "TBEAM_V0P7";
    case 7: return "T_ECHO";
    case 8: return "TLORA_V1_1P3";
    case 9: return "RAK4631";
    case 10: return "HELTEC_V2_1";
    case 11: return "HELTEC_V1";
    case 12: return "LILYGO_TBEAM_S3_CORE";
    case 13: return "RAK11200";
    case 14: return "NANO_G1";
    case 15: return "TLORA_V2_1_1P8";
    case 16: return "TLORA_T3_S3";
    case 17: return "NANO_G1_EXPLORER";
    case 18: return "NANO_G2_ULTRA";
    case 19: return "LORA_TYPE";
    case 20: return "WIPHONE";
    case 21: return "WIO_WM1110";
    case 22: return "RAK2560";
    case 23: return "HELTEC_HRU_3601";
    case 24: return "HELTEC_WIRELESS_BRIDGE";
    case 25: return "STATION_G1";
    case 26: return "RAK11310";
    case 27: return "SENSELORA_RP2040";
    case 28: return "SENSELORA_S3";
    case 29: return "CANARYONE";
    case 30: return "RP2040_LORA";
    case 31: return "STATION_G2";
    case 32: return "LORA_RELAY_V1";
    case 33: return "T_ECHO_PLUS";
    case 34: return "PPR";
    case 35: return "GENIEBLOCKS";
    case 36: return "NRF52_UNKNOWN";
    case 37: return "PORTDUINO";
    case 38: return "ANDROID_SIM";
    case 39: return "DIY_V1";
    case 40: return "NRF52840_PCA10059";
    case 41: return "DR_DEV";
    case 42: return "M5STACK";
    case 43: return "HELTEC_V3";
    case 44: return "HELTEC_WSL_V3";
    case 45: return "BETAFPV_2400_TX";
    case 46: return "BETAFPV_900_NANO_TX";
    case 47: return "RPI_PICO";
    case 48: return "HELTEC_WIRELESS_TRACKER";
    case 49: return "HELTEC_WIRELESS_PAPER";
    case 50: return "T_DECK";
    case 51: return "T_WATCH_S3";
    case 52: return "PICOMPUTER_S3";
    case 53: return "HELTEC_HT62";
    case 54: return "EBYTE_ESP32_S3";
    case 55: return "ESP32_S3_PICO";
    case 56: return "CHATTER_2";
    case 57: return "HELTEC_WIRELESS_PAPER_V1_0";
    case 58: return "HELTEC_WIRELESS_TRACKER_V1_0";
    case 59: return "UNPHONE";
    case 60: return "TD_LORAC";
    case 61: return "CDEBYTE_EORA_S3";
    case 62: return "TWC_MESH_V4";
    case 63: return "NRF52_PROMICRO_DIY";
    case 64: return "RADIOMASTER_900_BANDIT_NANO";
    case 65: return "HELTEC_CAPSULE_SENSOR_V3";
    case 66: return "HELTEC_VISION_MASTER_T190";
    case 67: return "HELTEC_VISION_MASTER_E213";
    case 68: return "HELTEC_VISION_MASTER_E290";
    case 69: return "HELTEC_MESH_NODE_T114";
    case 70: return "SENSECAP_INDICATOR";
    case 71: return "TRACKER_T1000_E";
    case 72: return "RAK3172";
    case 73: return "WIO_E5";
    case 74: return "RADIOMASTER_900_BANDIT";
    case 75: return "ME25LS01_4Y10TD";
    case 76: return "RP2040_FEATHER_RFM95";
    case 77: return "M5STACK_COREBASIC";
    case 78: return "M5STACK_CORE2";
    case 79: return "RPI_PICO2";
    case 80: return "M5STACK_CORES3";
    case 81: return "SEEED_XIAO_S3";
    case 82: return "MS24SF1";
    case 83: return "TLORA_C6";
    case 84: return "WISMESH_TAP";
    case 85: return "ROUTASTIC";
    case 86: return "MESH_TAB";
    case 87: return "MESHLINK";
    case 88: return "XIAO_NRF52_KIT";
    case 89: return "THINKNODE_M1";
    case 90: return "THINKNODE_M2";
    case 91: return "T_ETH_ELITE";
    case 92: return "HELTEC_SENSOR_HUB";
    case 93: return "MUZI_BASE";
    case 94: return "HELTEC_MESH_POCKET";
    case 95: return "SEEED_SOLAR_NODE";
    case 96: return "NOMADSTAR_METEOR_PRO";
    case 97: return "CROWPANEL";
    case 98: return "LINK_32";
    case 99: return "SEEED_WIO_TRACKER_L1";
    case 100: return "SEEED_WIO_TRACKER_L1_EINK";
    case 101: return "MUZI_R1_NEO";
    case 102: return "T_DECK_PRO";
    case 103: return "T_LORA_PAGER";
    case 104: return "M5STACK_RESERVED";
    case 105: return "WISMESH_TAG";
    case 106: return "RAK3312";
    case 107: return "THINKNODE_M5";
    case 108: return "HELTEC_MESH_SOLAR";
    case 109: return "T_ECHO_LITE";
    case 110: return "HELTEC_V4";
    case 111: return "M5STACK_C6L";
    case 112: return "M5STACK_CARDPUTER_ADV";
    case 113: return "HELTEC_WIRELESS_TRACKER_V2";
    case 114: return "T_WATCH_ULTRA";
    case 115: return "THINKNODE_M3";
    case 116: return "WISMESH_TAP_V2";
    case 117: return "RAK3401";
    case 118: return "RAK6421";
    case 119: return "THINKNODE_M4";
    case 120: return "THINKNODE_M6";
    case 121: return "MESHSTICK_1262";
    case 122: return "TBEAM_1_WATT";
    case 123: return "T5_S3_EPAPER_PRO";
    case 124: return "TBEAM_BPF";
    case 125: return "MINI_EPAPER_S3";
    case 126: return "TDISPLAY_S3_PRO";
    case 127: return "HELTEC_MESH_NODE_T096";
    case 128: return "TRACKER_T1000_E_PRO";
    case 129: return "THINKNODE_M7";
    case 130: return "THINKNODE_M8";
    case 131: return "THINKNODE_M9";
    case 132: return "HELTEC_V4_R8";
    case 133: return "HELTEC_MESH_NODE_T1";
    case 134: return "STATION_G3";
    case 135: return "T_IMPULSE_PLUS";
    case 136: return "T_ECHO_CARD";
    case 255: return "PRIVATE_HW";
    default: return "UNKNOWN";
  }
}

bool hardware_model_is_deprecated(uint32_t value) {
  (void) value;
  return false;
}

}  // namespace meshtastic
}  // namespace esphome
