#!/usr/bin/env python3
"""Generate components/meshtastic/_enums.py. Maps YAML enum names to nanopb C symbols from Meshtastic protobuf."""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

from google.protobuf import descriptor_pb2

TARGETS = {
    "meshtastic.Config.DeviceConfig.Role": "ROLES",
    "meshtastic.Config.LoRaConfig.RegionCode": "REGIONS",
    "meshtastic.Config.LoRaConfig.ModemPreset": "MODEM_PRESETS",
    "meshtastic.PortNum": "PORTNUMS",
    "meshtastic.HardwareModel": "HARDWARE_MODELS",
}

ROOT_PROTOS = [
    "meshtastic/config.proto",
    "meshtastic/portnums.proto",
    "meshtastic/mesh.proto",
]


def build_descriptor_set(proto_root: Path) -> descriptor_pb2.FileDescriptorSet:
    with tempfile.NamedTemporaryFile(suffix=".pb") as tmp:
        subprocess.run(
            ["protoc", f"-I{proto_root}", "--include_imports",
             f"--descriptor_set_out={tmp.name}", *ROOT_PROTOS],
            check=True,
        )
        fds = descriptor_pb2.FileDescriptorSet()
        fds.ParseFromString(Path(tmp.name).read_bytes())
        return fds


def walk_enums(fds):
    """Yield (full_name, EnumDescriptorProto) for every enum, nested included."""
    def recurse(msg, scope):
        path = f"{scope}.{msg.name}"
        for en in msg.enum_type:
            yield f"{path}.{en.name}", en
        for nested in msg.nested_type:
            yield from recurse(nested, path)

    for f in fds.file:
        scope = f.package
        for en in f.enum_type:
            yield f"{scope}.{en.name}", en
        for msg in f.message_type:
            yield from recurse(msg, scope)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--proto-root", default="meshtastic-protobufs", type=Path)
    ap.add_argument("--out", default="components/meshtastic/_enums.py", type=Path)
    args = ap.parse_args()

    fds = build_descriptor_set(args.proto_root)

    found = {}
    for full_name, en in walk_enums(fds):
        if full_name not in TARGETS:
            continue
        entries = {}
        for v in en.value:
            if v.options.deprecated:
                continue
            entries[v.name] = v.number
        found[TARGETS[full_name]] = entries

    missing = set(TARGETS.values()) - set(found)
    if missing:
        print(f"ERROR: enums not found in descriptors: {sorted(missing)}", file=sys.stderr)
        return 1

    lines = [
        "# GENERATED by `make gen` from the meshtastic-protobufs submodule. DO NOT EDIT.",
        "# Maps YAML enum name -> proto enum value; [deprecated] values omitted.",
        "",
    ]
    for name in TARGETS.values():
        lines.append(f"{name} = {{")
        for key, num in found[name].items():
            lines.append(f'    "{key}": {num},')
        lines.append("}")
        lines.append("")

    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out} ({', '.join(f'{k}={len(v)}' for k, v in found.items())})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
