#!/usr/bin/env python3
"""Generate components/meshtastic/_enums.py. Maps YAML enum names to nanopb C symbols from Meshtastic protobuf."""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

from google.protobuf import descriptor_pb2

TARGETS = {
    "meshtastic.Config.DeviceConfig.Role": "ROLES",
    "meshtastic.Config.LoRaConfig.RegionCode": "REGIONS",
    "meshtastic.Config.LoRaConfig.ModemPreset": "MODEM_PRESETS",
    "meshtastic.PortNum": "PORTNUMS",
    "meshtastic.HardwareModel": "HARDWARE_MODELS",
}

# Enums that also get a C++ number->name lookup (enum_names.{h,cpp}) for naming RECEIVED packets.
CPP_NAME_TARGETS = {
    "meshtastic.Config.DeviceConfig.Role": "role_name",
    "meshtastic.HardwareModel": "hardware_model_name",
}

ROOT_PROTOS = [
    "meshtastic/config.proto",
    "meshtastic/portnums.proto",
    "meshtastic/mesh.proto",
]


def build_descriptor_set(proto_root: Path) -> descriptor_pb2.FileDescriptorSet:
    with tempfile.NamedTemporaryFile(suffix=".pb") as tmp:
        subprocess.run(
            ["protoc", f"-I{proto_root}", "--include_imports", f"--descriptor_set_out={tmp.name}", *ROOT_PROTOS],
            check=True,
        )
        fds = descriptor_pb2.FileDescriptorSet()
        fds.ParseFromString(Path(tmp.name).read_bytes())
        return fds


def walk_enums(fds):
    """Yield (full_name, EnumDescriptorProto) for every enum, nested included."""

    def recurse(msg, scope):
        path = f"{scope}.{msg.name}"
        for en in msg.enum_type:
            yield f"{path}.{en.name}", en
        for nested in msg.nested_type:
            yield from recurse(nested, path)

    for f in fds.file:
        scope = f.package
        for en in f.enum_type:
            yield f"{scope}.{en.name}", en
        for msg in f.message_type:
            yield from recurse(msg, scope)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--proto-root", default="meshtastic-protobufs", type=Path)
    ap.add_argument("--out", default="components/meshtastic/_enums.py", type=Path)
    args = ap.parse_args()

    fds = build_descriptor_set(args.proto_root)

    found = {}
    cpp_found = {}
    cpp_deprecated = {}
    for full_name, en in walk_enums(fds):
        if full_name in TARGETS:
            entries = {}
            for v in en.value:
                entries[v.name] = v.number
            found[TARGETS[full_name]] = entries
        if full_name in CPP_NAME_TARGETS:
            pairs = {}  # number -> name; first name wins on any alias
            deprecated = []
            for v in en.value:
                pairs.setdefault(v.number, v.name)
                if v.options.deprecated:
                    deprecated.append(v.number)
            cpp_found[CPP_NAME_TARGETS[full_name]] = pairs
            cpp_deprecated[CPP_NAME_TARGETS[full_name]] = deprecated

    missing = (set(TARGETS.values()) - set(found)) | (set(CPP_NAME_TARGETS.values()) - set(cpp_found))
    if missing:
        print(f"ERROR: enums not found in descriptors: {sorted(missing)}", file=sys.stderr)
        return 1

    lines = [
        "# GENERATED by `make gen` from the meshtastic-protobufs submodule. DO NOT EDIT.",
        "# Maps YAML enum name -> proto enum value",
        "",
    ]
    for name in TARGETS.values():
        lines.append(f"{name} = {{")
        for key, num in found[name].items():
            lines.append(f'    "{key}": {num},')
        lines.append("}")
        lines.append("")

    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out} ({', '.join(f'{k}={len(v)}' for k, v in found.items())})")

    # C++ number->name lookups for naming received enum fields (role, hw_model).
    banner = "// GENERATED by `make gen` from the meshtastic-protobufs submodule. DO NOT EDIT."
    h_lines = [
        banner,
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace esphome {",
        "namespace meshtastic {",
        "",
    ]
    c_lines = [banner, '#include "enum_names.h"', "", "namespace esphome {", "namespace meshtastic {", ""]
    for func, pairs in cpp_found.items():
        base = func[: -len("_name")]  # role_name -> role
        h_lines.append(f"const char *{func}(uint32_t value);")
        h_lines.append(f"bool {base}_is_deprecated(uint32_t value);")
        c_lines.append(f"const char *{func}(uint32_t value) {{")
        c_lines.append("  switch (value) {")
        for num, vname in sorted(pairs.items()):
            c_lines.append(f'    case {num}: return "{vname}";')
        c_lines.append('    default: return "UNKNOWN";')
        c_lines.append("  }")
        c_lines.append("}")
        c_lines.append("")
        dep = sorted(cpp_deprecated.get(func, []))
        c_lines.append(f"bool {base}_is_deprecated(uint32_t value) {{")
        if dep:
            c_lines.append("  switch (value) {")
            for num in dep:
                c_lines.append(f"    case {num}:")
            c_lines.append("      return true;")
            c_lines.append("    default:")
            c_lines.append("      return false;")
            c_lines.append("  }")
        else:
            c_lines.append("  (void) value;")
            c_lines.append("  return false;")
        c_lines.append("}")
        c_lines.append("")
    h_lines += ["", "}  // namespace meshtastic", "}  // namespace esphome", ""]
    c_lines += ["}  // namespace meshtastic", "}  // namespace esphome", ""]
    out_dir = args.out.parent
    (out_dir / "enum_names.h").write_text("\n".join(h_lines))
    (out_dir / "enum_names.cpp").write_text("\n".join(c_lines))
    print(f"wrote enum_names.h/.cpp ({', '.join(f'{k}={len(v)}' for k, v in cpp_found.items())})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
